### ISSUE TITLE
Problem installing TRES

### ISSUE THREAD

**Issue by ignotur** [amusecode/TRES#4]
Dear All,

I have installed amuse following the recommendations: https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html
Next, I have successfully installed SeBa inside amuse.

Now I am trying to install TRES and receive the following error:
/Users/amtai/Amuse-env/share/amuse/bin/amusifier --type=c interface.py SecularTripleInterface -o worker_code.cc
make: /Users/amtai/Amuse-env/share/amuse/bin/amusifier: No such file or directory
make: *** [worker_code.cc] Error 1

Indeed, I have no bin/amusifier  
It is unclear to me how to proceed. This is all I have in the folder:
ls /Users/amtai/Amuse-env/share/amuse/   
config.mk	lib

**Comment by rieder** [comment]
Have you activated your AMUSE virtual environment?
You may need to run `./configure` in the AMUSE root dir, and then run `make framework`.

**Comment by ignotur** [comment]
For some weird reasons amusifier --get-amuse-dir returns /Users/amtai/amuse/share/amuse while it does not have any /bin subfolder. Instead /Users/amtai/amuse/bin/amusifier is the correct path to amusifier

ls /Users/amtai/amuse/share/amuse/
config.mk	lib

But I have managed to install the TRES using by substituting the correct path to the Makefile.
